import type { PhoneConfig } from './types'
const contact = (id: string, name: string, initials: string, color: string, photo?: string) => ({ id, name, initials, color, photo })
export const phones: Record<PhoneConfig['id'], PhoneConfig> = {
  a: { id:'a', label:'Reina', role:'Master', battery:91, signalBars:2, wifi:true, muted:true, unreadMessages:1, unreadVoicemails:0, flashlight:false, wallpaper:'#d8dce4', 
    contacts:{ b:{...contact('b','KyunYong','KY','#918ac8'),groupPhoto:'images/avatars/kyunyong.jpg'}, 
               tom:contact('tom','Tom 💗','💕','#648f85'), 
               starr:contact('starr','Mr. Starr','🫡','#8e8392'), 
               jack:contact('jack','Jack-o-lantern','🎃','#b09b75'), 
               gail:contact('gail','Gail','G','#8a9aad'), 
               ash:contact('ash','Ash','A','#bb907a'), 
               james:contact('james','James','J','#8a9aad'), 
               eddie:contact('eddie','Eddie','E','#bb907a'),
               lucifer:contact('lucifer','Lucifer','😈','#bb907a'),
               hermione:contact('hermione','Hermione','H','#bb907a'),}, 
    threads:[
      {id:'a-tom',app:'messages',title:'Tom 💗',participants:['a','tom'],preview:"Yeah I think I'll do a Trader Joes run today",time:'9:41'},
      {id:'a-starr',app:'messages',title:'Mr. Starr',participants:['a','starr'],preview:'Checking in.',time:'9:35'},
      {id:'a-b',app:'messenger',title:'KyunYong',participants:['a','b'],preview:'Open to read',time:'Yesterday',pinned:true,photo:'images/avatars/kyunyong.jpg'},
      {id:'a-soldiers',app:'messages',title:"starr's child soldiers",participants:['b','a','james','eddie'],preview:'who named this chat',time:'9:38',group:true,groupIcon:'🥷'},
      {id:'a-family',app:'messages',title:'starry night fam',participants:['b','a','starr'],preview:'Please answer.',time:'9:13',group:true,groupIcon:'👨🏻‍👧🏻‍👧🏻'},
      {id:'a-james',app:'messages',title:'James',participants:['a','james'],preview:"yaa I'm really hyped for all the kbbq omg",time:'4:44'},
      {id:'a-jacky',app:'messages',title:'Jack-o-Lantern',participants:['a','jack'],preview:'You loved "Happy Halloween 🎃"',time:'1:10'},
      {id:'a-ash',app:'messages',title:'Ash',participants:['a','ash'],preview:"but I had a whole dinner date planned, pls convince her",time:'Yesterday', unread:1},
      {id:'a-gail',app:'messages',title:'Gail',participants:['a','gail'],preview:"Idk what's going on but it's prolly ash's fault",time:'Thursday'},
      {id:'a-eddie',app:'messages',title:'Eddie',participants:['a','eddie'],preview:'Eddie liked "Send me your itinerary when you have a chance!"',time:'Wednesday'},
      {id:'a-lucifer',app:'messages',title:'Lucifer',participants:['a','lucifer'],preview:'You loved "come say hi if you swing by hell on halloween!"',time:'Tuesday'},
      {id:'a-hermione',app:'messages',title:'Hermione',participants:['a','hermione'],preview:"I don't think it's safe to attempt another portal this year",time:'Monday'},
    ] },
  b: { id:'b', label:'KyunYong', role:'Controller', battery:12, signalBars:4, wifi:true, muted:false, unreadMessages:21, unreadVoicemails:8, flashlight:false, wallpaper:'#cfc6d7', 
    contacts:{ a:{...contact('a','Reina','R','#738dab'),groupPhoto:'images/avatars/reina.jpg'}, 
               starr:contact('starr','daddy ⭐️','⭐','#b09b75'), 
               jack:contact('jack','jacky chan 🎃','🎃','#b09b75'), 
               james:contact('james','James','J','#8a9aad'), 
               eddie:contact('eddie','Eddie','E','#bb907a'), 
               gail:contact('gail','Gail','G','#8a9aad'), 
               ash:contact('ash','Ash','A','#bb907a'), 
               mandy:contact('mandy','Mandy','M','#bb907a'), 
               yoochan:contact('yoochan','Yoochan','Y','#bb907a'), 
               amy:contact('amy','Amy','A','#648f85'), }, 
    threads:[
      {id:'b-a',app:'messenger',title:'Reina',participants:['b','a'],preview:'Drafts (3)',time:'Now',unread:4,pinned:true,photo:'images/avatars/reina.jpg'},
      {id:'b-soldiers',app:'messages',title:"starr's child soldiers",participants:['b','a','james','eddie'],preview:'who named this chat',time:'9:38',group:true,groupIcon:'🥷'},
      {id:'b-family',app:'messages',title:'starry night fam',participants:['b','a','starr'],preview:'Please answer.',time:'9:13',group:true,groupIcon:'👨🏻‍👧🏻‍👧🏻'},
      {id:'b-starr',app:'messages',title:'daddy ⭐️',participants:['b','starr'],preview:'Call me.',time:'9:10'},
      {id:'b-eddie',app:'messages',title:'eddie',participants:['b','eddie'],preview:'You emphasized "idk how friendly korea is to gay couples tho"',time:'9:04'},
      {id:'b-amy',app:'messages',title:'amy',participants:['b','amy'],preview:'ㅋㅋ',time:'8:10',unread:3},
      {id:'b-jack',app:'messages',title:'jacky chan 🎃',participants:['b','jack'],preview:'You loved "Happy Halloween 🎃"',time:'1:10'},
      {id:'b-james',app:'messages',title:'james',participants:['b','james'],preview:'bruh',time:'Yesterday',unread:2},
      {id:'b-yoochan',app:'messages',title:'yoochan',participants:['b','yoochan'],preview:'how did the date go??',time:'Yesterday',unread:1},
      {id:'b-mandy',app:'messages',title:'mandy',participants:['b','mandy'],preview:'skill issue bro',time:'Yesterday'},
      {id:'b-ash',app:'messages',title:'ash',participants:['b','ash'],preview:'You emphasized "do you wanna get dinner on sunday?"',time:'Thursday'},
      {id:'b-gail',app:'messages',title:'gail',participants:['b','gail'],preview:'ash wants me to tell you to stop ignoring him',time:'Wednesday', unread: 1},
      
    ] },
  jack: { id:'jack', label:'Jack 🎃', role:'Bloopers! Read last', battery:64, signalBars:3, wifi:true, muted:false, unreadMessages:31, unreadVoicemails:66, flashlight:true, wallpaper:'#cfbf9f', 
    contacts:{ unknown:contact('unknown','Unknown','?','#646b73'),
               a:{...contact('a','Reina','R','#738dab'),groupPhoto:'images/avatars/reina.jpg'},
               b:{...contact('b','KyunYong','K','#cfc6d7'),groupPhoto:'images/avatars/kyunyong.jpg'},
               starr:contact('starr','Starr','⭐','#b09b75'),
               gary:contact('gary', 'Gary', 'G', '#738dab'),
               sue:contact('sue', 'Sue Vaughan', 'S', '#b09b75') }, 
    threads:[
        {id:'jack-unknown',app:'messages',title:'Unknown',participants:['jack','unknown'],preview:'New message',time:'Now',unread:1,unknown:true},
        {id:'jack-a', app:'messages',title:'Reina',participants:['jack', 'a'],preview:'Happy Halloween 🎃',time:'1:10'},
        {id:'jack-b', app:'messages',title:'KyunYong',participants:['jack', 'b'],preview:'Happy Halloween 🎃',time:'1:10'},
        {id:'jack-starr', app:'messages',title:'Starr',participants:['jack', 'starr'],preview:'Happy Halloween 🎃',time:'1:10'},
        {id:'jack-gary', app:'messages',title:'Gary',participants:['jack', 'gary'],preview:'Happy Halloween 🎃',time:'1:10'},
        {id:'jack-sue', app:'messages',title:'Sue Vaughan',participants:['jack', 'sue'],preview:'Happy Halloween 🎃🕊️',time:'1:10'},
  ] },
}
