import type { StoryRoute } from '../types'
export const aStory: StoryRoute = { id:'a', events:[
  {id:'a-01',type:'openApp',app:'messages',cue:'Open Messages'},
  {id:'a-02',type:'openThread',threadId:'a-starr',cue:'Open Mr. Starr'},
  {id:'a-03',type:'message',cue:'Mr. Starr checks in',message:{id:'a-m1',threadId:'a-starr',sender:'starr',text:'Are you two on your way?',timestamp:'9:41',app:'messages',status:'delivered'}},
  {id:'a-04',type:'message',cue:'Reina replies',message:{id:'a-m2',threadId:'a-starr',sender:'a',text:'Almost. Everything is under control.',timestamp:'9:42',app:'messages',status:'read'}},
  {id:'a-05',type:'inbox',app:'messages',cue:'Back to the inbox'},
  {id:'a-06',type:'appSwitch',app:'messenger',cue:'Switch to Messenger'},
  {id:'a-07',type:'openThread',threadId:'a-b',cue:'Open KyunYong'},
  {id:'a-08',type:'message',cue:'Reina asks KyunYong',message:{id:'a-m3',threadId:'a-b',sender:'a',text:'Did you get the address?',timestamp:'9:43',app:'messenger',status:'delivered'}},
  {id:'a-09',type:'typing',sender:'KyunYong',active:true,cue:'KyunYong is typing…'},
  {id:'a-10',type:'typing',sender:'KyunYong',active:false,cue:'Typing stops'},
  {id:'a-11',type:'typing',sender:'KyunYong',active:true,cue:'KyunYong is typing again…'},
  {id:'a-12',type:'typing',sender:'KyunYong',active:false,cue:'Typing stops again'},
  {id:'a-13',type:'typing',sender:'KyunYong',active:true,cue:'One more attempt…'},
  {id:'a-14',type:'typing',sender:'KyunYong',active:false,cue:'And stops'},
  {id:'a-15',type:'pause',duration:1200,cue:'A quiet moment'},
  {id:'a-16',type:'message',cue:'KyunYong finally sends',message:{id:'a-m4',threadId:'a-b',sender:'b',text:'nvm',timestamp:'9:44',app:'messenger',status:'read',compromised:true,shadow:true}},
  {id:'a-17',type:'glitch',target:'messenger',effect:'signal',cue:'A brief signal drop'},
  {id:'a-18',type:'notification',app:'Messages',from:'Tom',text:"do you want anything from trader joe's",cue:'Tom checks in'},
  {id:'a-19',type:'inbox',app:'messenger',cue:'Back to Messenger inbox'},
  {id:'a-20',type:'appSwitch',app:'messages',cue:'Return to Messages'},
  {id:'a-21',type:'inbox',app:'messages',cue:'Messages inbox'},
  {id:'a-22',type:'openThread',threadId:'a-soldiers',cue:'Open the group chat'},
  {id:'a-23',type:'message',cue:'James checks in',message:{id:'a-m5',threadId:'a-soldiers',sender:'james',text:'Is this the correct group?',timestamp:'9:45',app:'messages',status:'delivered'}},
  {id:'a-24',type:'message',cue:'Eddie replies',message:{id:'a-m6',threadId:'a-soldiers',sender:'eddie',text:'The name suggests otherwise.',timestamp:'9:45',app:'messages',status:'delivered'}},
  {id:'a-25',type:'call',contact:'KyunYong',direction:'outgoing',outcome:'failed',cue:'Reina’s call fails'},
  {id:'a-26',type:'complete',cue:'End of Reina’s demo'},
] }
