import type { StoryRoute } from '../types'
export const bStory: StoryRoute = { id:'b', events:[
  {id:'b-01',type:'openApp',app:'messages',cue:'Open Messages'},
  {id:'b-02',type:'openThread',threadId:'b-family',cue:'Open Starry Night Family'},
  {id:'b-03',type:'message',cue:'A family reminder',message:{id:'b-m1',threadId:'b-family',sender:'starr',text:'Please answer when you arrive.',timestamp:'9:40',app:'messages',status:'delivered'}},
  {id:'b-04',type:'inbox',app:'messages',cue:'Back to the messy inbox'},
  {id:'b-05',type:'notification',app:'DoorDash',from:'DoorDash',text:'Your order has been picked up.',cue:'Delivery update'},
  {id:'b-06',type:'appSwitch',app:'messenger',cue:'Switch to Messenger'},
  {id:'b-07',type:'openThread',threadId:'b-a',cue:'Open Reina'},
  {id:'b-08',type:'message',cue:'Reina’s question arrives',message:{id:'b-m2',threadId:'b-a',sender:'a',text:'Did you get the address?',timestamp:'9:43',app:'messenger',status:'read'}},
  {id:'b-09',type:'message',cue:'KyunYong drafts a reply',message:{id:'b-draft1',threadId:'b-a',sender:'b',text:'I think the map is wrong.',timestamp:'9:43',app:'messenger',status:'sent',compromised:true}},
  {id:'b-10',type:'removeMessage',messageId:'b-draft1',cue:'KyunYong unsends it'},
  {id:'b-11',type:'message',cue:'KyunYong tries again',message:{id:'b-draft2',threadId:'b-a',sender:'b',text:'Wait, I found something.',timestamp:'9:44',app:'messenger',status:'sent',compromised:true}},
  {id:'b-12',type:'removeMessage',messageId:'b-draft2',cue:'KyunYong unsends that too'},
  {id:'b-13',type:'message',cue:'Only this reaches Reina',message:{id:'b-m3',threadId:'b-a',sender:'b',text:'nvm',timestamp:'9:44',app:'messenger',status:'delivered',compromised:true,shadow:true}},
  {id:'b-14',type:'glitch',target:'messenger',effect:'smudge',cue:'A shadow passes'},
  {id:'b-15',type:'inbox',app:'messenger',cue:'Back to Messenger inbox'},
  {id:'b-16',type:'appSwitch',app:'messages',cue:'Return to Messages'},
  {id:'b-17',type:'openThread',threadId:'b-soldiers',cue:'Open the group chat'},
  {id:'b-18',type:'message',cue:'A group question',message:{id:'b-m4',threadId:'b-soldiers',sender:'b',text:'Who named this chat?',timestamp:'9:46',app:'messages',status:'read'}},
  {id:'b-19',type:'notes',title:'Reminder',body:'Buy batteries. Ask why we need batteries.',cue:'Open Notes'},
  {id:'b-20',type:'findMy',person:'Reina',status:'Location unavailable',cue:'Check Find My'},
  {id:'b-21',type:'call',contact:'Reina',direction:'incoming',outcome:'ringing',cue:'Incoming call from Reina'},
  {id:'b-21b',type:'call',contact:'Reina',direction:'incoming',outcome:'declined',cue:'Call declined'},
  {id:'b-22',type:'complete',cue:'End of KyunYong’s demo'},
] }
